name: runtime-versions.yml

on:
  pull_request:
    paths:
      - README.md
      - package.json

jobs:
  check_runtime_versions:
    runs-on: ubuntu-latest

    steps:
      - run: yq --help

      - id: versions
        run: |
          PHP_VERSION=`yq -f extract '.php' README.md`
          NODE_VERSION=`yq -f extract '.["node.js"]' README.md`
          echo "php=${PHP_VERSION}" >> "$GITHUB_OUTPUT"
          echo "node=${NODE_VERSION}" >> "$GITHUB_OUTPUT"

      - id: parsedPackageJSON
        uses: mikefarah/yq@master
        with:
          cmd: yq '.engines.node' 'package.json'

      - name: Check package.json NODE Version
        if: ${{ !contains(steps.parsedPackageJSON.outputs.result, steps.versions.outputs.node) }}
        run: echo 'package.json use not valid node version'
          exit 1
